defmodule EulerWithElixir.P2 do
  @problem_description """
  Each new term in the Fibonacci sequence is generated by adding 
  the previous two terms. By starting with 1 and 2, the first 10 
  terms will be:
  
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  
  By considering the terms in the Fibonacci sequence whose values 
  do not exceed four million, find the sum of the even-valued 
  terms.
  """
  @limit 4_000_000

  defp fibonaccis_below(a, b, lst) when a >= @limit, do: lst
  defp fibonaccis_below(a, b, lst) do
    fibonaccis_below(b, a+b, [a+b|lst])
  end

  def solution do
    import Enum

    fibonaccis_below(1, 2, [2, 1])
      |> filter(&(0 == rem(&1, 2)))
      |> filter(&(@limit >= &1))
      |> reduce(&+/2)
  end
end
